name: Daily News Agent (SendGrid with Categories)

on:
  schedule:
    - cron: "30 1 * * *"  # Runs at 7 AM IST (1:30 UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run news agent
        run: python news_agent.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          NEWS_CATEGORIES: ${{ secrets.NEWS_CATEGORIES }}
	  WORLDNEWS_API_KEY: ${{ secrets.WORLDNEWS_API_KEY }}
